"""Shared directory-merkle hashing for the deployed-tree path.

Three sites on the deployed-tree path need one directory digest, and
before this module none of them shared code or an exclusion filter:

===========================================  ========  ==============
Site                                         Role      Hashes
===========================================  ========  ==============
``packs/handlers/skill.py:_stage_dir_copy``  write     source tree
``compose_packs.py:_dir_sha256``             read      deployed tree
``packs/uninstall.py:_dir_sha256``           read      deployed tree
===========================================  ========  ==============

The write site hashes the **source** tree while both read sites hash the
**target**, so the scheme holds only while the deployed directory stays
byte-identical to its source. Any tool that writes inside a deployed
skill directory breaks that invariant. CPython is the common culprit:
importing a script from ``.claude/skills/<name>/scripts/`` leaves a
``__pycache__`` behind, the directory hash changes, and
``_build_prior_pack_outputs`` then refuses to walk the directory. Every
file in the skill falls to ``PRESTATE_UNMANAGED`` and the drift gate
aborts the next compose with ``rc=1``, naming files the user never
touched and telling them to back up edits that do not exist
(anywhere-agents#18). The same stray file makes ``pack uninstall``
report drift and refuse to remove the directory.

Encoding
--------

Two ambiguities had to be closed, and both were found by reproducing a
digest collision rather than by reading the code.

**Content could impersonate a file boundary.** The pre-#18 encoding
concatenated ``rel_posix + NUL + content + NUL`` per file. Paths cannot
contain NUL, which is what the old comment claimed made the framing
unambiguous, but **file content can**::

    one file   a = b"x\\0b\\0y"      -> a\\0x\\0b\\0y\\0
    two files  a = b"x", b = b"y"   -> a\\0x\\0b\\0y\\0

Both hashed to ``dir-sha256:938fbc10...``, and a directory swapped
between those shapes passed ``_delete_project_local`` with
``drift_paths=[]`` and was removed. Explicit 8-byte length prefixes fix
this: the byte stream parses back into exactly one sequence of fields.

**A filename could impersonate a directory separator.** Joining the
relative path into a single ``a/b`` string is ambiguous on POSIX, where
a backslash is a legal filename character: a file literally named
``a\\b`` normalized to the same string as file ``b`` inside directory
``a``, and length prefixes did not help because the collision happened
before the framing. Reproduced on a real Linux filesystem, both yielding
``cc5c4287...``. Paths are therefore encoded **component-wise**: a
component count, then each component length-prefixed. Separators never
enter the byte stream, so no filename can forge one.

Components come from :attr:`pathlib.PurePath.parts` on the real relative
path, not from splitting a joined string, which is the distinction the
bug turned on. ``a/b`` yields two components on every platform, so
digests stay identical across Windows and POSIX for ordinary names.

:data:`DIRHASH_V2_DOMAIN` prefixes the stream so this digest cannot
collide with another SHA-256 the project computes.

Versioning
----------

Digests are self-identifying: :func:`dir_sha256` emits
``dir-sha256-v2:<hex>`` and :func:`legacy_dir_sha256` keeps the bare
``dir-sha256:<hex>`` that shipped versions wrote. Without that, the two
forms shared one namespace and :func:`matches_any` had to try the
colliding legacy encoder on *every* read, including locks already
rewritten under v2, which kept the collision reachable forever. Now the
recorded string selects its own encoder and a migrated lock leaves the
legacy path behind for good.

:func:`legacy_dir_sha256` is read-only. Nothing writes it any more; it
exists so a lock recorded by a shipped pre-#18 version still verifies.
See :func:`matches_any`.

Scope, and why the ignore-list is short
---------------------------------------

The filter is not for tidiness. It is an ignore-list on a gate that
authorizes ``shutil.rmtree``: whatever it covers can be deleted by
``pack uninstall`` with no drift warning, and is dropped from a pack's
deployed copy without an error. So it holds only regenerable tool caches
and OS droppings, never anything that could be a user's sole copy.

Two categories were tried here and moved out after review reproduced
silent deletion of both:

* Editor and VCS recovery files. A ``~`` backup, a ``.swp`` swap, a
  ``.orig`` original, a ``.rej`` hunk, a notebook checkpoint, and a
  *file* named ``.git`` (a submodule gitdir pointer) can each hold work
  that exists nowhere else. Standalone ``.pyc`` files are content too,
  since PEP 3147 puts generated bytecode inside ``__pycache__``.
* ``.git/`` directories and ``.dir-sha256``. A real ``.git/`` holds
  local-only objects, refs, stashes, and reflogs; ``.git/refs/stash``
  vanished with no drift reported. ``.dir-sha256`` is product-owned only
  at an archive-cache **root**, so excluding the name at any depth also
  dropped a nested ``docs/.dir-sha256`` that the cache side treats as
  content. Both are now content here. Archive-root metadata is filtered
  at the copy site instead, in ``handlers/skill.py``, where the archive
  root is actually known.

The list is deliberately incomplete rather than speculative. Other tools
write into working trees too (Coverage.py's ``.coverage`` is the common
one) and those files are treated as content, so they cause conservative
drift: uninstall refuses, which is noisy but safe. Adding a name here
converts that into silent deletion, so a name earns its place only when
losing the file costs nothing.

``packs/source_fetch.py`` deliberately does **not** use this predicate.
Its hash guards the archive cache, where any file can be a manifest's
``files[].from`` source; a manifest may legitimately read
``hook.py.orig`` and deploy it as ``deployed.py``. Ignoring a name there
would let mutated cache bytes pass the integrity check, so that side
keeps its own conservative rule. It carries its own copy of the v2
framing for the same reason; ``tests/test_dirhash_artifacts.py`` pins the
two encoders equal so the duplication cannot drift.

Only the hash input and the deployed copy are filtered, and they are
filtered identically. Every other source file is copied and compared
byte for byte, so a genuine user edit keeps aborting exactly as before.
"""
from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Iterator

# Directory names whose entire subtree is regenerable tool state. Matched
# on parent components only, so a *file* carrying one of these names
# stays content.
EXCLUDED_DIR_NAMES = frozenset({
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
})

# Exact file names that are OS droppings.
EXCLUDED_FILE_NAMES = frozenset({
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
})

# Prefix for every v2 digest. Distinguishes this hash from any other
# SHA-256 the project computes and from the pre-#18 encoding.
DIRHASH_V2_DOMAIN = b"anywhere-agents-dir-sha256-v2\0"

# Width of the length prefixes. 8 bytes covers any real file.
_LEN_BYTES = 8

# Digest label written by :func:`dir_sha256`, and the bare label shipped
# versions wrote. A recorded value's label selects the encoder used to
# verify it, which is what keeps a migrated lock off the legacy path.
V2_PREFIX = "dir-sha256-v2:"
LEGACY_PREFIX = "dir-sha256:"


def is_dir_digest(value: str) -> bool:
    """Return True for a directory digest in either format.

    Call sites that used to test ``startswith("dir-sha256:")`` must use
    this instead: the v2 label is *not* a prefix-extension of the legacy
    one, so a bare ``startswith`` silently drops every v2 value.
    """
    return value.startswith(V2_PREFIX) or value.startswith(LEGACY_PREFIX)


def is_artifact_parts(parts: tuple[str, ...] | list[str]) -> bool:
    """Return True when a path's components name regenerable tool state.

    Directory names are tested against parent components only, so a
    final component that happens to match a directory name stays
    content.
    """
    if not parts:
        return False
    if any(part in EXCLUDED_DIR_NAMES for part in parts[:-1]):
        return True
    return parts[-1] in EXCLUDED_FILE_NAMES


def is_artifact(rel_posix: str) -> bool:
    """String convenience wrapper over :func:`is_artifact_parts`.

    Only safe for paths that are already known to be separator-clean.
    A caller holding a real path should pass its ``parts``: on POSIX a
    filename may contain a backslash, and on any platform this split
    cannot tell a one-component name from a two-component path that
    happens to render the same way.
    """
    return is_artifact_parts(rel_posix.split("/"))


def iter_content_files(
    root: Path, *, filtered: bool = True
) -> Iterator[tuple[Path, str, tuple[str, ...]]]:
    """Yield ``(absolute_path, rel_posix, rel_parts)`` under ``root``.

    ``rel_parts`` comes from :attr:`pathlib.PurePath.parts` and is the
    authoritative form: it is what filtering and hashing use, because a
    joined string cannot be split back reliably. ``rel_posix`` is kept
    for messages and for callers that only need a display form.

    Results are unordered; callers that hash must sort by ``rel_parts``.
    ``filtered=False`` applies no exclusion, which the legacy hash needs.
    """
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        parts = rel.parts
        if filtered and is_artifact_parts(parts):
            continue
        yield path, str(rel).replace("\\", "/"), parts


def new_dir_hasher() -> "hashlib._Hash":
    """Return a hasher primed with the v2 domain tag."""
    hasher = hashlib.sha256()
    hasher.update(DIRHASH_V2_DOMAIN)
    return hasher


def update_dir_hasher(
    hasher, rel_parts: tuple[str, ...] | list[str], content: bytes
) -> None:
    """Absorb one file into a hasher from :func:`new_dir_hasher`.

    The path is encoded component-wise (count, then each component
    length-prefixed) and the content is length-prefixed, so the stream
    parses back into exactly one file set. Passing a pre-joined string
    would reopen the separator ambiguity this framing exists to close.

    Exposed so ``handlers/skill.py`` can hash and copy in one pass; a
    file set that differed between the two would record a digest no read
    site could reproduce.
    """
    hasher.update(len(rel_parts).to_bytes(_LEN_BYTES, "big"))
    for part in rel_parts:
        part_bytes = part.encode("utf-8")
        hasher.update(len(part_bytes).to_bytes(_LEN_BYTES, "big"))
        hasher.update(part_bytes)
    hasher.update(len(content).to_bytes(_LEN_BYTES, "big"))
    hasher.update(content)


def dir_sha256(root: Path) -> str:
    """Return the current ``dir-sha256-v2:<hex>`` digest for ``root``.

    Content files sorted by their component tuple, so the sort key and
    the hash input are the same object and the order is reproducible
    across filesystems whose ``rglob`` order differs. Raises ``OSError``
    on permission errors; callers handle it.
    """
    hasher = new_dir_hasher()
    for path, _rel_posix, parts in sorted(
        iter_content_files(root), key=lambda item: item[2]
    ):
        update_dir_hasher(hasher, parts, path.read_bytes())
    return f"{V2_PREFIX}{hasher.hexdigest()}"


def legacy_dir_sha256(root: Path) -> str:
    """Reproduce the pre-anywhere-agents#18 digest for ``root``.

    Unfiltered walk, ``rel_posix + NUL + content + NUL`` per file. Read
    only: nothing writes this form any more. It exists so a lock or
    marker recorded by a shipped pre-#18 version still verifies against
    an unchanged tree, including whatever artifact was present when that
    version copied it.

    This encoding carries both ambiguities described in the module
    docstring, so it must never verify a value some other encoder
    produced. :func:`matches_any` reaches it only for a recorded string
    that carries the legacy label, which bounds the exposure to locks an
    older version actually wrote.

    Its bytes are frozen by definition. Changing anything here, however
    reasonable the change looks, silently invalidates every pre-#18
    lock.
    """
    hasher = hashlib.sha256()
    for path, rel_posix, _parts in sorted(
        iter_content_files(root, filtered=False), key=lambda item: item[1]
    ):
        hasher.update(rel_posix.encode("utf-8"))
        hasher.update(b"\0")
        hasher.update(path.read_bytes())
        hasher.update(b"\0")
    return f"{LEGACY_PREFIX}{hasher.hexdigest()}"


def matches_any(root: Path, known: set[str]) -> bool:
    """Return True when ``root`` matches a recorded digest in ``known``.

    Each recorded value selects its own encoder from its label, so a
    value written under v2 is never checked with the legacy encoder.
    That is the point of labelling them: while both forms shared one
    namespace, every read had to try the colliding legacy encoder, which
    kept the collision reachable even for locks already migrated.

    This is not a bypass. Each branch is an exact digest comparison over
    the current tree, so an edit to any non-excluded file still aborts.
    The gate's real width is :func:`is_artifact_parts`, which is why
    that list is kept short.

    The legacy branch is a compatibility floor, not a migration. It
    matches only while the tree is byte-identical to what the old
    version copied, artifact included; once that artifact is rewritten
    or removed, neither form matches and the directory needs one
    successful compose to be re-recorded under v2.
    """
    v2_known = {v for v in known if v.startswith(V2_PREFIX)}
    if v2_known and dir_sha256(root) in v2_known:
        return True
    legacy_known = {v for v in known if v.startswith(LEGACY_PREFIX)}
    return bool(legacy_known) and legacy_dir_sha256(root) in legacy_known
